/**
 * @NApiVersion 2.1
 * @NScriptType UserEventScript
 * @NModuleScope SameAccount
 *
 * This file has been autogenerated in a local CI environment
 * @governance 527 Units
 */
define([
    '../../../../../ARKA_SUE_AddSyncQuoteButton.js',
    '../../../../../ARKA_SUE_AutodeskNxmFieldValidation.js',
    '../../../../../ARKA_SUE_BluebeamHandleDynamicSalesRep.js',
    '../../../../../ARKA_SUE_CalculateExtendedCostAndPoRate.js',
    '../../../../../ARKA_SUE_CheckOutsideItemGroup.js',
    '../../../../../ARKA_SUE_CreateContactManagerField.js',
    '../../../../../ARKA_SUE_DatechFieldValidation.js',
    '../../../../../ARKA_SUE_DisplayWarningEstMessage.js',
    '../../../../../ARKA_SUE_DuplicateEstimate.js',
    '../../../../../ARKA_SUE_LimitTransactionStatus.js',
    '../../../../../ARKA_SUE_NBEPersonas.js',
    '../../../../../ARKA_SUE_RenewalProcessEshopNetSuite.js',
    '../../../../../ARKA_SUE_SetContractNumber.js',
    '../../../../../ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.js',
    '../../../../../ARKA_SUE_TransactionDepValidation.js',
    '../../../../../ARKA_SUE_WarningOnTransaction.js',
], function (
    ARKA_SUE_AddSyncQuoteButton,
    ARKA_SUE_AutodeskNxmFieldValidation,
    ARKA_SUE_BluebeamHandleDynamicSalesRep,
    ARKA_SUE_CalculateExtendedCostAndPoRate,
    ARKA_SUE_CheckOutsideItemGroup,
    ARKA_SUE_CreateContactManagerField,
    ARKA_SUE_DatechFieldValidation,
    ARKA_SUE_DisplayWarningEstMessage,
    ARKA_SUE_DuplicateEstimate,
    ARKA_SUE_LimitTransactionStatus,
    ARKA_SUE_NBEPersonas,
    ARKA_SUE_RenewalProcessEshopNetSuite,
    ARKA_SUE_SetContractNumber,
    ARKA_SUE_SetExpectedCloseDateFieldOnEstimate,
    ARKA_SUE_TransactionDepValidation,
    ARKA_SUE_WarningOnTransaction
) {
    // Display simply entry points detected as functions

    const beforeLoad = (scriptContext) => {
        log.debug({
            title: 'UserEventScript',
            details: {
                title: 'Running the beforeLoad entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                scriptsLoaded: [
                    'ARKA_SUE_AddSyncQuoteButton',
                    'ARKA_SUE_AutodeskNxmFieldValidation',
                    'ARKA_SUE_BluebeamHandleDynamicSalesRep',
                    'ARKA_SUE_CalculateExtendedCostAndPoRate',
                    'ARKA_SUE_CheckOutsideItemGroup',
                    'ARKA_SUE_CreateContactManagerField',
                    'ARKA_SUE_DatechFieldValidation',
                    'ARKA_SUE_DisplayWarningEstMessage',
                    'ARKA_SUE_DuplicateEstimate',
                    'ARKA_SUE_LimitTransactionStatus',
                    'ARKA_SUE_NBEPersonas',
                    'ARKA_SUE_RenewalProcessEshopNetSuite',
                    'ARKA_SUE_SetContractNumber',
                    'ARKA_SUE_SetExpectedCloseDateFieldOnEstimate',
                    'ARKA_SUE_TransactionDepValidation',
                    'ARKA_SUE_WarningOnTransaction',
                ],
            },
        })
        if (typeof ARKA_SUE_AddSyncQuoteButton.beforeLoad === 'function') {
            ARKA_SUE_AddSyncQuoteButton.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_AutodeskNxmFieldValidation.beforeLoad === 'function') {
            ARKA_SUE_AutodeskNxmFieldValidation.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_BluebeamHandleDynamicSalesRep.beforeLoad === 'function') {
            ARKA_SUE_BluebeamHandleDynamicSalesRep.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_CalculateExtendedCostAndPoRate.beforeLoad === 'function') {
            ARKA_SUE_CalculateExtendedCostAndPoRate.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_CheckOutsideItemGroup.beforeLoad === 'function') {
            ARKA_SUE_CheckOutsideItemGroup.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_CreateContactManagerField.beforeLoad === 'function') {
            ARKA_SUE_CreateContactManagerField.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_DatechFieldValidation.beforeLoad === 'function') {
            ARKA_SUE_DatechFieldValidation.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_DisplayWarningEstMessage.beforeLoad === 'function') {
            ARKA_SUE_DisplayWarningEstMessage.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_DuplicateEstimate.beforeLoad === 'function') {
            ARKA_SUE_DuplicateEstimate.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_LimitTransactionStatus.beforeLoad === 'function') {
            ARKA_SUE_LimitTransactionStatus.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_NBEPersonas.beforeLoad === 'function') {
            ARKA_SUE_NBEPersonas.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.beforeLoad === 'function') {
            ARKA_SUE_RenewalProcessEshopNetSuite.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_SetContractNumber.beforeLoad === 'function') {
            ARKA_SUE_SetContractNumber.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.beforeLoad === 'function') {
            ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_TransactionDepValidation.beforeLoad === 'function') {
            ARKA_SUE_TransactionDepValidation.beforeLoad(scriptContext)
        }
        if (typeof ARKA_SUE_WarningOnTransaction.beforeLoad === 'function') {
            ARKA_SUE_WarningOnTransaction.beforeLoad(scriptContext)
        }
    }

    const beforeSubmit = (scriptContext) => {
        log.debug({
            title: 'UserEventScript',
            details: {
                title: 'Running the beforeSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                scriptsLoaded: [
                    'ARKA_SUE_AddSyncQuoteButton',
                    'ARKA_SUE_AutodeskNxmFieldValidation',
                    'ARKA_SUE_BluebeamHandleDynamicSalesRep',
                    'ARKA_SUE_CalculateExtendedCostAndPoRate',
                    'ARKA_SUE_CheckOutsideItemGroup',
                    'ARKA_SUE_CreateContactManagerField',
                    'ARKA_SUE_DatechFieldValidation',
                    'ARKA_SUE_DisplayWarningEstMessage',
                    'ARKA_SUE_DuplicateEstimate',
                    'ARKA_SUE_LimitTransactionStatus',
                    'ARKA_SUE_NBEPersonas',
                    'ARKA_SUE_RenewalProcessEshopNetSuite',
                    'ARKA_SUE_SetContractNumber',
                    'ARKA_SUE_SetExpectedCloseDateFieldOnEstimate',
                    'ARKA_SUE_TransactionDepValidation',
                    'ARKA_SUE_WarningOnTransaction',
                ],
            },
        })
        if (typeof ARKA_SUE_AddSyncQuoteButton.beforeSubmit === 'function') {
            ARKA_SUE_AddSyncQuoteButton.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_AutodeskNxmFieldValidation.beforeSubmit === 'function') {
            ARKA_SUE_AutodeskNxmFieldValidation.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_BluebeamHandleDynamicSalesRep.beforeSubmit === 'function') {
            ARKA_SUE_BluebeamHandleDynamicSalesRep.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CalculateExtendedCostAndPoRate.beforeSubmit === 'function') {
            ARKA_SUE_CalculateExtendedCostAndPoRate.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CheckOutsideItemGroup.beforeSubmit === 'function') {
            ARKA_SUE_CheckOutsideItemGroup.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CreateContactManagerField.beforeSubmit === 'function') {
            ARKA_SUE_CreateContactManagerField.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DatechFieldValidation.beforeSubmit === 'function') {
            ARKA_SUE_DatechFieldValidation.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DisplayWarningEstMessage.beforeSubmit === 'function') {
            ARKA_SUE_DisplayWarningEstMessage.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DuplicateEstimate.beforeSubmit === 'function') {
            ARKA_SUE_DuplicateEstimate.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_LimitTransactionStatus.beforeSubmit === 'function') {
            ARKA_SUE_LimitTransactionStatus.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_NBEPersonas.beforeSubmit === 'function') {
            ARKA_SUE_NBEPersonas.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.beforeSubmit === 'function') {
            ARKA_SUE_RenewalProcessEshopNetSuite.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_SetContractNumber.beforeSubmit === 'function') {
            ARKA_SUE_SetContractNumber.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.beforeSubmit === 'function') {
            ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_TransactionDepValidation.beforeSubmit === 'function') {
            ARKA_SUE_TransactionDepValidation.beforeSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_WarningOnTransaction.beforeSubmit === 'function') {
            ARKA_SUE_WarningOnTransaction.beforeSubmit(scriptContext)
        }
    }

    const afterSubmit = (scriptContext) => {
        log.debug({
            title: 'UserEventScript',
            details: {
                title: 'Running the afterSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                scriptsLoaded: [
                    'ARKA_SUE_AddSyncQuoteButton',
                    'ARKA_SUE_AutodeskNxmFieldValidation',
                    'ARKA_SUE_BluebeamHandleDynamicSalesRep',
                    'ARKA_SUE_CalculateExtendedCostAndPoRate',
                    'ARKA_SUE_CheckOutsideItemGroup',
                    'ARKA_SUE_CreateContactManagerField',
                    'ARKA_SUE_DatechFieldValidation',
                    'ARKA_SUE_DisplayWarningEstMessage',
                    'ARKA_SUE_DuplicateEstimate',
                    'ARKA_SUE_LimitTransactionStatus',
                    'ARKA_SUE_NBEPersonas',
                    'ARKA_SUE_RenewalProcessEshopNetSuite',
                    'ARKA_SUE_SetContractNumber',
                    'ARKA_SUE_SetExpectedCloseDateFieldOnEstimate',
                    'ARKA_SUE_TransactionDepValidation',
                    'ARKA_SUE_WarningOnTransaction',
                ],
            },
        })
        if (typeof ARKA_SUE_AddSyncQuoteButton.afterSubmit === 'function') {
            ARKA_SUE_AddSyncQuoteButton.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_AutodeskNxmFieldValidation.afterSubmit === 'function') {
            ARKA_SUE_AutodeskNxmFieldValidation.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_BluebeamHandleDynamicSalesRep.afterSubmit === 'function') {
            ARKA_SUE_BluebeamHandleDynamicSalesRep.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CalculateExtendedCostAndPoRate.afterSubmit === 'function') {
            ARKA_SUE_CalculateExtendedCostAndPoRate.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CheckOutsideItemGroup.afterSubmit === 'function') {
            ARKA_SUE_CheckOutsideItemGroup.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_CreateContactManagerField.afterSubmit === 'function') {
            ARKA_SUE_CreateContactManagerField.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DatechFieldValidation.afterSubmit === 'function') {
            ARKA_SUE_DatechFieldValidation.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DisplayWarningEstMessage.afterSubmit === 'function') {
            ARKA_SUE_DisplayWarningEstMessage.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_DuplicateEstimate.afterSubmit === 'function') {
            ARKA_SUE_DuplicateEstimate.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_LimitTransactionStatus.afterSubmit === 'function') {
            ARKA_SUE_LimitTransactionStatus.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_NBEPersonas.afterSubmit === 'function') {
            ARKA_SUE_NBEPersonas.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.afterSubmit === 'function') {
            ARKA_SUE_RenewalProcessEshopNetSuite.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_SetContractNumber.afterSubmit === 'function') {
            ARKA_SUE_SetContractNumber.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.afterSubmit === 'function') {
            ARKA_SUE_SetExpectedCloseDateFieldOnEstimate.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_TransactionDepValidation.afterSubmit === 'function') {
            ARKA_SUE_TransactionDepValidation.afterSubmit(scriptContext)
        }
        if (typeof ARKA_SUE_WarningOnTransaction.afterSubmit === 'function') {
            ARKA_SUE_WarningOnTransaction.afterSubmit(scriptContext)
        }
    }

    return {
        beforeLoad: beforeLoad,
        beforeSubmit: beforeSubmit,
        afterSubmit: afterSubmit,
    }
})
