/**
 * @NApiVersion 2.1
 * @NScriptType UserEventScript
 * @NModuleScope SameAccount
 *
 * This file has been autogenerated in a local CI environment
 * @governance 900 Units
 */
define(['../../../../../ARKA_SUE_RenewalProcessEshopNetSuite.js', '../../../../../ARKA_SUE_SetContractNumber.js'], (
    ARKA_SUE_RenewalProcessEshopNetSuite,
    ARKA_SUE_SetContractNumber
) => {
    // Display simply entry points detected as functions

    const afterSubmit = async (scriptContext) => {
        try {
            log.debug({
                title: 'UserEventScript',
                details: {
                    title: 'Running the afterSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    scriptsLoaded: ['ARKA_SUE_RenewalProcessEshopNetSuite', 'ARKA_SUE_SetContractNumber'],
                },
            })

            if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.afterSubmit === 'function') {
                await ARKA_SUE_RenewalProcessEshopNetSuite.afterSubmit(scriptContext)
            }
            if (typeof ARKA_SUE_SetContractNumber.afterSubmit === 'function') {
                await ARKA_SUE_SetContractNumber.afterSubmit(scriptContext)
            }
        } catch (err) {
            // On error catch, send message to all developpers
            log.error({
                title: 'UserEventScript',
                details: {
                    title: 'Error running the afterSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    error: err,
                },
            })
        }
    }

    const beforeLoad = async (scriptContext) => {
        try {
            log.debug({
                title: 'UserEventScript',
                details: {
                    title: 'Running the beforeLoad entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    scriptsLoaded: ['ARKA_SUE_RenewalProcessEshopNetSuite', 'ARKA_SUE_SetContractNumber'],
                },
            })

            if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.beforeLoad === 'function') {
                await ARKA_SUE_RenewalProcessEshopNetSuite.beforeLoad(scriptContext)
            }
            if (typeof ARKA_SUE_SetContractNumber.beforeLoad === 'function') {
                await ARKA_SUE_SetContractNumber.beforeLoad(scriptContext)
            }
        } catch (err) {
            // On error catch, send message to all developpers
            log.error({
                title: 'UserEventScript',
                details: {
                    title: 'Error running the beforeLoad entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    error: err,
                },
            })
        }
    }

    const beforeSubmit = async (scriptContext) => {
        try {
            log.debug({
                title: 'UserEventScript',
                details: {
                    title: 'Running the beforeSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    scriptsLoaded: ['ARKA_SUE_RenewalProcessEshopNetSuite', 'ARKA_SUE_SetContractNumber'],
                },
            })

            if (typeof ARKA_SUE_RenewalProcessEshopNetSuite.beforeSubmit === 'function') {
                await ARKA_SUE_RenewalProcessEshopNetSuite.beforeSubmit(scriptContext)
            }
            if (typeof ARKA_SUE_SetContractNumber.beforeSubmit === 'function') {
                await ARKA_SUE_SetContractNumber.beforeSubmit(scriptContext)
            }
        } catch (err) {
            // On error catch, send message to all developpers
            log.error({
                title: 'UserEventScript',
                details: {
                    title: 'Error running the beforeSubmit entrypoint from the dispatcher file ./FileCabinet/SuiteScripts/Codes/Scripts/Records/Estimate/User Event Scripts/ARKA_SUE_Est_dispatcher1',
                    error: err,
                },
            })
        }
    }

    return {
        afterSubmit: afterSubmit,
        beforeLoad: beforeLoad,
        beforeSubmit: beforeSubmit,
    }
})
