
            /**
             * @NApiVersion 2.1
             * @NScriptType UserEventScript
             * @NModuleScope SameAccount
             * 
             * This file has been autogenerated in a local CI environment
             */
            define([
                "../../../../../ARKA_SUE_NBEPersonas.js"
            ],

            function(
                ARKA_SUE_NBEPersonas
            ) {
                
                // Display simply entry points detected as functions
                
                    const beforeLoad = (scriptContext) => {
                        ARKA_SUE_NBEPersonas.beforeLoad(scriptContext);
                    };

                return {
                    beforeLoad: beforeLoad
                }
            });
        